name: Deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: Deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Package binary
        run: cp ./target/x86_64-unknown-linux-musl/release/lambda ./bootstrap && zip lambda.zip bootstrap && rm bootstrap
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_DEPLOY_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_DEPLOY_KEY }}
          aws_region: us-east-1
          function_name: annual_events
          zip_file: lambda.zip
          memory_size: 128
          runtime: provided.al2
